project:
  type: website

website:
  favicon: theme/logo/logo_light.png

  title: "U-KREAT"
  navbar:
    pinned: true
    logo: theme/logo/logo_dark.png
    left:
      - href: team.qmd
        text: Meet the team
      - href: projects.qmd
        text: Projects
      - href: highlights.qmd
        text: Output
      - href: blog/index.qmd
        text: Blog
    right:
      - href: resources.qmd
        text: Resources
      - href: calendar.qmd
        text: Calendar
      - href: contact.qmd
        text: Contact
  back-to-top-navigation: true

  sidebar:
    - title: "Resources"
      style: "floating"
      contents:
        - resources.qmd
        - section: "Journals"
          contents:
          - k-journals.qmd
          - g-journals.qmd
          - c-journals.qmd
          - d-journals.qmd
          - e-journals.qmd
    - title: "Output"
      style: "floating"
      contents:
        - "highlights.qmd" 
        - "publications.qmd"
        - "other_media.qmd"
        - "theses.qmd"

format:
  html:
    theme: 
      light: [styles/ukreat, styles/theme.scss]
      dark: [styles/ukreat, styles/theme_dark.scss]
    respect-user-color-scheme: true
    toc: true



